### ISSUE TITLE
Running more than 256 paths will cause traceflow to crash

### ISSUE THREAD

**Issue by rucarrol** [rucarrol/traceflow#27]
```Traceback (most recent call last):
  File "/usr/local/bin/traceflow", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/traceflow/__main__.py", line 175, in main
    ip_id = ints_to_ipid(path, ttl)
  File "/usr/local/lib/python3.7/site-packages/traceflow/__main__.py", line 29, in ints_to_ipid
    s = struct.pack("!H", (path << :heart_eyes: + ttl)
struct.error: 'H' format requires 0 <= number <= 65535```

**Comment by rucarrol** [comment]
fixed in commit 4d59bb287b2ade579fa19c841366865cea8ff48b
